### ISSUE TITLE
[`ceres-firebase`] Failed to resolve $firebase-module dependency

### ISSUE THREAD

**Issue by zeoowl-dev** [teogor/ceres#10]
**Please complete the following information:**

- Library Version: 1.0.0-alpha01

**Describe the Bug:**

With the `ceres-firebase` module added the below error is thrown:
```gradle
Failed to resolve: com.google.firebase:firebase-appindexing
```

**Expected Behavior:**

The project should build succesfully

**Comment by teogor** [comment]
We are using firebase bom to add the dependencies. For some reasons `com.vanniktech.maven.publish` does not recognize that dependency when uploading the library to maven.

**Comment by teogor** [comment]
It will be fixed in the next release

**Comment by teogor** [comment]
this is false positive. @zeoowl-dev please try to remove ´com.google.firebase:firebase-appindexing´ as it was deprecated

**Comment by zeoowl-dev** [comment]
yes, it does the trick! thanks, @teogor
