### ISSUE TITLE
[ADS] Native ad is not loading properly

### ISSUE THREAD

**Issue by zeoowl-dev** [teogor/ceres#23]
The native ad is not loading properly

**Comment by teogor** [comment]
I have debugged the issue that occurs in the `NativeAdView` and due to its problem, I classified this issue as `security-breach`

**Comment by teogor** [comment]
```kotlin
val binder = binder
root = adFrame
adFrame.removeAllViews()
if (binder.getAdView().parent != null) {
  (binder.getAdView().parent as ViewGroup).removeView(binder.getAdView())
}
adFrame.addView(binder.getAdView())
```

**Comment by teogor** [comment]
@zeoowl-dev: the fix was implemented. please subscribe to the repo to be notified when the next release is launched
