### ISSUE TITLE
AppOpenAd is not shown properly

### ISSUE THREAD

**Issue by zeoowl-dev** [teogor/ceres#55]
`AppOpenAd` is shown even when a new activity is launched. It should be shown when the app resumes from background only.

**Comment by teogor** [comment]
Indeed, nice catch! But some developers may want this bug (feature???) for some activities.

**Comment by teogor** [comment]
Therefore, this bug will be fixed but we will be adding a builder to flag that we want to show the `AppOpenAd` on some activities too

**Comment by zeoowl-dev** [comment]
yes, it is better that way

**Comment by teogor** [comment]
The `showAppOpenAd()` method was added in #59

**Comment by zeoowl-dev** [comment]
It works now! Thank you, @teogor
