### ISSUE TITLE
Live view does not show the elements properly

### ISSUE THREAD

**Issue by zeoflow-dev** [teogor/ceres#67]
This is how the `fragment_home.xml` looks like:

![image](https://user-images.githubusercontent.com/49202162/200221769-e9906248-4d62-4eee-8e40-3b82944e5f61.png)

The buttons do not have colors over them

**Comment by teogor** [comment]
We are looking to implement that when we migrate to compose.

**Comment by teogor** [comment]
Thank you for reporting this issue, @zeoflow-dev. We appreciate your patience and feedback.

We're delighted to inform you that the feature you reported has been successfully implemented as part of our migration to Jetpack Compose. Your contribution and feedback played a crucial role in making this enhancement possible.

Your continued involvement in our project is highly valued. If you encounter any more issues or have further insights to share, please don't hesitate to reach out. We're here to assist and improve our project together.
