### ISSUE TITLE
Invalid class extender - `Logger`

### ISSUE THREAD

**Issue by zeoflow-dev** [teogor/ceres#73]
Currently there are multiple classes that implement or extend the `Logger`. Even though this adds the option to `log($message)` from the base class, in case that it is not used it adds a new function to each of its parents.

I would recommend to look into `kotlin-extensions`

**Comment by teogor** [comment]
Indeed, that is a problem. This task was added to the `icebox` in `Open-Source Projects`

**Comment by zeoflow-dev** [comment]
Awesome! Thank you
