### ISSUE TITLE
Option to disable app-open-ads once only

### ISSUE THREAD

**Issue by zeoflow-dev** [teogor/ceres#79]
It would be nice if there was an option to disable the AppOpenAds once without flagging the activity

**Comment by teogor** [comment]
This will be useful in many cases for instance when changing the theme.

To disable it call `disableFirstAppOpenAd()` or if you want you can pass a boolean there too `disableFirstAppOpenAd(false/true)`

**Comment by zeoflow-dev** [comment]
Thank you, @teogor
